### ISSUE TITLE
Eslint Install Issue

### ISSUE THREAD

**Issue by nhattrinh** [d4nh-Le/dyscroller#2]
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: eslint-plugin-import@2.29.1
npm error Found: eslint@9.9.0
npm error node_modules/eslint
npm error   dev eslint@"^9.9.0" from the root project
npm error   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm error   node_modules/@eslint-community/eslint-utils
npm error     @eslint-community/eslint-utils@"^4.2.0" from eslint@9.9.0
npm error   2 more (eslint-plugin-react, eslint-webpack-plugin)
npm error
npm error Could not resolve dependency:
npm error peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8" from eslint-plugin-import@2.29.1
npm error node_modules/eslint-plugin-import
npm error   dev eslint-plugin-import@"^2.29.1" from the root project
npm error
npm error Conflicting peer dependency: eslint@8.57.0
npm error node_modules/eslint
npm error   peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8" from eslint-plugin-import@2.29.1
npm error   node_modules/eslint-plugin-import
npm error     dev eslint-plugin-import@"^2.29.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\Nhat\AppData\Local\npm-cache\_logs\2024-08-12T19_39_01_710Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\Nhat\AppData\Local\npm-cache\_logs\2024-08-12T19_39_01_710Z-debug-0.log

**Comment by d4nh-Le** [comment]
use 

npm install --legacy-peer-deps

we have all dependencies needed so do this npm will ignore the version checks of dependencies
